### ISSUE TITLE
Unable to hide sensitive content

### ISSUE THREAD

**Issue by leadra** [rod24574575/monorepo#1]
![image](https://github.com/rod24574575/monorepo/assets/67009996/0f74e0df-3a55-4cd5-8110-4711889fcac8)
https://twitter.com/hsiungmao/status/1779912393390481879

**Comment by rod24574575** [comment]
我在 Chrome 和 Firefox 開啟該連結，看起來敏感內容警告都有被正確隱藏。能請你提供像是瀏覽器版本等更多資訊嗎？另外也請你試試看在無痕視窗下，把其他附加元件都停用，只留下 stylus 並只啟用 twitter-hide-warning 的情況下，是否還是會遇到此問題呢？

**Comment by leadra** [comment]
晚回復很抱歉，還是搞不清楚git通知提醒會顯示在哪
後來我的推特突然就沒有"敏感內容警告"了...
沒開腳本也都找不到，現在網址都被強制轉x.com了

**Comment by rod24574575** [comment]
前一陣子用還是 twitter.com ，但現在看起來的確都會被轉址到 x.com 了，而敏感內容警告好像也不再出現了。如果之後還有再出現敏感內容警告的話我會再更新腳本。
